version: '3.8'
services:
  event_db:
    image: mysql:8.0
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 53306:3306
    volumes:
      - ./data:/var/lib/mysql
